"""
Constantes del proyecto para evitar magic numbers y strings.
"""

# Configuración de clientes
CLIENTE_LAP = 1
CLIENTE_ACC = 2

# Drivers de base de datos
SQL_SERVER_DRIVER = 'SQL Server'

# Rangos de celdas Excel - ReliquidacionEFACT
EXCEL_HEADER_ROW = 8
EXCEL_DATA_START_ROW = 9
EXCEL_DATA_END_ROW = 14
EXCEL_TOTAL_ROW = 15

# Rangos extendidos para archivos temporales
EXCEL_TEMP_DATA_END_ROW = 65
EXCEL_TEMP_TOTAL_ROW = 66

# Columnas Excel
COL_FECHA = 'B'
COL_ORIGEN_DATA_FACTURADO = 'C'
COL_ENERGIA_FACTURADA = 'D'
COL_ORIGEN_DATA_DEFINITIVO = 'L'
COL_ENERGIA_DEFINITIVA = 'M'
COL_RELIQUIDACION_MENSUAL = 'V'
COL_DIAS_INTERESES = 'AB'
COL_INTERES_TOTAL = 'AC'
COL_INTERESES = 'AD'
COL_RELIQUIDACION_TOTAL = 'AE'

# Estilos Excel
EXCEL_COLUMN_WIDTH = 18
EXCEL_HEADER_COLOR = '9BBB59'
EXCEL_FONT_COLOR = 'FFFFFF'
EXCEL_FONT_SIZE = 11
EXCEL_BORDER_COLOR = '393939'

# Formatos de número
FORMAT_CURRENCY = '$#,##0'
FORMAT_CURRENCY_DECIMAL = '#,##0.00'
FORMAT_DECIMAL_4 = '#,##0.0000'
FORMAT_DECIMAL_0 = '#,##0.0'
FORMAT_DATE = 'DD-MM-YYYY'

# IDs de agrupaciones a excluir
AGRUPACIONES_EXCLUIDAS = [12, 19, 20]

# Tipos de PNP
PNP_ITD = 'ITD'

# Códigos de artículo para facturación
CODIGO_ENERGIA = 'VENTA PPA ENERGIA'
CODIGO_POTENCIA = 'VENTA PPA POTENCIA'

# Conceptos SIGGE
CONCEPTO_ENERGIA = 'Energía'
CONCEPTO_POTENCIA = 'Potencia'

# Nombres de hojas Excel
SHEET_README = 'README'
SHEET_RELIQ_EFACT = 'ReliquidacionEFACT'
SHEET_RELIQ_CEN = 'ReliquidacionCEN'
SHEET_RESUMEN_RETIROS = 'ResumenRetiros'
SHEET_FACT_EMITIDA = 'FACT_EMITIDA'
SHEET_SIGGE_E = 'SIGGE_E'
SHEET_SIGGE_P = 'SIGGE_P'
SHEET_FACT_EST_EFACT = 'FACT_EST_EFACT'
SHEET_FACT_REAL = 'FACT_REAL'
SHEET_EFACT_CNE = 'EFACT_CNE'
SHEET_EFACT_CNE_BT = 'EfactCNE_BT'
SHEET_CEN_ENERGIA = 'CEN_Energia'
SHEET_CEN_POTENCIA = 'CEN_Potencia'
SHEET_CEN_ENERGIA_BT = 'CEN_EnergiaBT'
SHEET_EFACT_EST_CEN = 'EFACT_EST_CEN'
SHEET_SIN_DATA = 'SIN_DATA'
SHEET_INTERESES = 'INTERESES'
SHEET_RESUMEN = 'Resumen'

# Prefijos de templates
TEMPLATE_PREFIX = 'Template_'
TEMPLATE_EXTENSION = '.xlsx'
